config/routes.rb
get 'roadmap/versions',                      :to => 'roadmap#index'
get 'projects/:project_id/roadmap/versions', :to => 'roadmap#index', :as => 'roadmap_project_versions'
resources :version_statuses

app/controllers/roadmap_controller.rb
class RoadmapController < ApplicationController
    menu_item :versions

    helper :queries
    include QueriesHelper
    helper :custom_fields
    include CustomFieldsHelper

    before_action :find_optional_project, :check_visibility

    def index
        retrieve_query(VersionQuery, false)
        if @query.valid?
            scope = @query.results_scope
            respond_to do |format|
                format.html {
                    @version_count = scope.count
                    @version_pages = Paginator.new(@version_count, per_page_option, params['page'])
                    @versions = scope.offset(@version_pages.offset).limit(@version_pages.per_page).to_a
                }
                format.atom {
                    versions = scope.limit(Setting.feeds_limit.to_i).to_a
                    render_feed(versions, :title => "#{@project || Setting.app_title}: #{l(:label_version_plural)}")
                }
                format.csv  {
                    send_data(query_to_csv(scope.to_a, @query, params[:csv]), :type => 'text/csv; header=present', :filename => 'versions.csv')
                }
                format.pdf  {
                    @versions = scope.to_a
                    send_file_headers!(:type => 'application/pdf', :filename => 'versions.pdf')
                }
            end
        else
            respond_to do |format|
                format.html
                format.any(:atom, :csv, :pdf) { head 422 }
            end
        end
    end

private

    def find_optional_project
        @project = Project.find(params[:project_id]) unless params[:project_id].blank?
    rescue ActiveRecord::RecordNotFound
        render_404
    end

    def check_visibility
        render_403 unless User.current.allowed_to?(:view_issues, @project, :global => true)
    end

end

app/helpers/roadmap_helper.rb
module RoadmapHelper
    include Redmine::Export::PDF::IssuesPdfHelper

    # Wrapper around QueriesHelper#column_content (calls version_column_value)
    def version_column_content(column, item)
        if column.name == :default_version
            version_column_value(column, item, item == item.project.default_version)
        elsif column.name == :done_ratio
            version_column_value(column, item, [ item.closed_percent, item.completed_percent ])
        else
            value = column.value_object(item)
            if value.is_a?(Array)
                values = value.collect{ |v| version_column_value(column, item, v) }.compact
                safe_join(values, ', ')
            else
                version_column_value(column, item, value)
            end
        end
    end

    # Wrapper around QueriesHelper#column_value
    def version_column_value(column, item, value)
        case column.name
        when :name
            link_to(value, version_path(item))
        when :status
            item.status_name.capitalize
        when :sharing
            l("label_version_sharing_#{value}")
        when :wiki_page_title
            if value.present? && !item.project.wiki.nil? && User.current.allowed_to?(:view_wiki_pages, item.project)
                link_to(value, { :controller => 'wiki', :action => 'show', :project_id => item.project, :id => Wiki.titleize(value) })
            else
                value
            end
        when :default_version
            checked_image value
        when :done_ratio
            progress_bar(value)
        when :estimated_duration, :duration, :remaining_duration
            l('datetime.distance_in_words.x_days', :count => value) if value
        when :extra_duration
            if value
                css_classes = [ 'duration' ]
                if value > 0
                    css_classes << 'overdue'
                elsif value < 0
                    css_classes << 'early'
                end
                content_tag('span', l('datetime.distance_in_words.x_days', :count => value), :class => css_classes.join(' '))
            end
        else
            column_value(column, item, value)
        end
    end

    def version_column_label(column, value)
        case column
        when :status
            l("version_status_#{value}").capitalize
        when :sharing
            l("label_version_sharing_#{value}")
        else
            value
        end
    end

    def version_css_classes(version)
        css_classes = [ 'version', cycle('odd', 'even'), version.status ]
        css_classes << (version.completed? ? 'completed' : 'incompleted')
        unless version.closed?
            css_classes << 'behind-schedule' if version.behind_schedule?
            css_classes << 'overdue' if version.overdue?
        end
        css_classes << 'shared' if version.shared?
        css_classes
    end

    # We are reusing #calc_col_width - that's why we need to fake #issue_list
    def version_list(versions, &block)
        versions.each do |version|
            yield version, 0
        end
    end
    alias :issue_list :version_list

    # Alias some functions from IssuesPdfHelper for readability (and to avoid confusion)
    alias :get_versions_to_pdf_write_cells :get_issues_to_pdf_write_cells
    alias :versions_to_pdf_write_cells     :issues_to_pdf_write_cells

    # Rewrite of #fetch_row_values in IssuesPdfHelper
    def fetch_version_values(version, query)
        query.inline_columns.collect do |column|
            result = if column.is_a?(QueryCustomFieldColumn)
                custom_value = version.visible_custom_field_values.detect{ |value| value.custom_field_id == column.custom_field.id }
                show_value(custom_value, false)
            else
                value = version_column_label(column.name, version.send(column.name))
                if value.is_a?(Date)
                    format_date(value)
                elsif value.is_a?(Time)
                    format_time(value)
                elsif value.is_a?(Float)
                    sprintf('%.2f', value)
                else
                    value
                end
            end
            result.to_s
        end
    end

    # Many things copied from #issues_to_pdf
    def versions_to_pdf(versions, project, query)
        pdf = Redmine::Export::PDF::ITCPDF.new(current_language, 'L')
        title = query.new_record? ? l(:label_version_plural) : query.name
        title = "#{project} - #{title}" if project
        pdf.set_title(title)
        pdf.alias_nb_pages
        pdf.footer_date = format_date(User.current.today)
        pdf.set_auto_page_break(false)
        pdf.add_page('L')

        # Landscape A4 = 210 x 297 mm
        page_height   = pdf.get_page_height # 210
        page_width    = pdf.get_page_width  # 297
        left_margin   = pdf.get_original_margins['left'] # 10
        right_margin  = pdf.get_original_margins['right'] # 10
        bottom_margin = pdf.get_footer_margin
        row_height    = 4

        col_width   = []
        table_width = page_width - right_margin - left_margin
        unless query.inline_columns.empty?
            col_width   = calc_col_width(versions, query, table_width, pdf)
            table_width = col_width.inject(0, :+)
        end

        pdf.SetFontStyle('B', 11)
        pdf.RDMCell(190, 8, title)
        pdf.ln

        totals = query.totals.map{ |column, total| "#{column.caption}: #{total}" }
        if totals.present?
            pdf.SetFontStyle('B', 10)
            pdf.RDMCell(table_width, 6, totals.join('  '), 0, 1, 'R')
        end

        render_table_header(pdf, query, col_width, row_height, table_width)

        previous_group = false
        totals_by_group = query.totals_by_group
        result_count_by_group = query.result_count_by_group

        versions.each do |version|
            if query.grouped? && (group = query.group_by_column.value(version)) != previous_group
                pdf.SetFontStyle('B', 10)
                group_label = group.blank? ? 'None' : version_column_label(query.group_by_column.name, group.to_s.dup)
                group_label << " (#{result_count_by_group[group]})"
                pdf.bookmark(group_label, 0, -1)
                pdf.RDMCell(table_width, row_height * 2, group_label, 'LR', 1, 'L')
                pdf.SetFontStyle('', 8)

                totals = totals_by_group.map{ |column, total| "#{column.caption}: #{total[group]}"}.join('  ')
                pdf.RDMCell(table_width, row_height, totals, 'LR', 1, 'L') if totals.present?
                previous_group = group
            end

            col_values = fetch_version_values(version, query)

            base_y     = pdf.get_y
            max_height = get_versions_to_pdf_write_cells(pdf, col_values, col_width)
            space_left = page_height - base_y - bottom_margin
            if max_height > space_left
                pdf.add_page("L")
                render_table_header(pdf, query, col_width, row_height, table_width)
                base_y = pdf.get_y
            end

            versions_to_pdf_write_cells(pdf, col_values, col_width, max_height)
            pdf.set_y(base_y + max_height)
        end

        pdf.output
    end

end

app/views/roadmap/_list.html.erb
<div class="autoscroll">
  <table class="list odd-even versions">
    <thead>
      <% @query.inline_columns.each do |column| %>
        <%= column_header(@query, column) %>
      <% end %>
      <th></th>
    </thead>
    <tbody>
      <% grouped_query_results(versions, @query) do |version, group_name, group_count, group_totals| %>
        <% if group_name %>
          <% reset_cycle %>
          <tr class="group open">
            <td colspan="<%= @query.inline_columns.size + 1 %>">
              <span class="expander icon icon-expended" onclick="toggleRowGroup(this);">&nbsp;</span>
              <span class="name"><%= version_column_label(@query.group_by_column.name, group_name) %></span>
              <% if group_count %><span class="badge badge-count count"><%= group_count %></span><% end %>
              <span class="totals"><%= group_totals %></span>
              <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}", 'toggleAllRowGroups(this)', :class => 'toggle-all') %>
            </td>
          </tr>
        <% end %>
        <% css_classes = version_css_classes(version) %>
        <tr id="version-<%= version.id %>" class="<%= css_classes.join(' ') %>">
          <% @query.inline_columns.each do |column| %>
            <%= content_tag('td', version_column_content(column, version), :class => column.css_classes) %>
          <% end %>
          <td class="buttons">
            <% if User.current.allowed_to?(:manage_versions, version.project) %>
              <%= link_to(l(:button_edit), edit_version_path(version), :class => 'icon-only icon-edit') %>
              <%= delete_link(version_path(version, :back_url => request.original_fullpath), :class => 'icon-only icon-del') %>
            <% end %>
          </td>
        </tr>
        <% @query.block_columns.each do |column| %>
          <% if (text = version_column_content(column, version)) && text.present? %>
            <tr class="<%= css_classes.join(' ') %>">
              <td colspan="<%= @query.inline_columns.size + 1 %>" class="<%= column.css_classes %>">
                <% if @query.block_columns.count > 1 %><span><%= column.caption %></span><% end %>
                <%= text %>
              </td>
            </tr>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/roadmap/index.html.erb
<div class="contextual">
  <%= link_to(l(:label_version_new), new_project_version_path(@project),
              :class => 'icon icon-add') if @project && User.current.allowed_to?(:manage_versions, @project) %>
</div>

<%= title(l(:label_version_plural)) %>

<%= form_tag(@project ? roadmap_project_versions_path(@project) : roadmap_versions_path, :method => :get, :id => 'query_form') do %>
  <%= render :partial => 'queries/query_form' %>
<% end %>

<% if @query.valid? %>
  <% if @versions.present? %>
    <%= render_query_totals(@query) %>
    <%= render :partial => 'list', :locals => { :versions => @versions } %>
    <span class="pagination"><%= pagination_links_full(@version_pages, @version_count) %></span>
  <% else %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% end %>
<% end %>

<% other_formats_links do |f| %>
  <%= f.link_to_with_query_parameters('Atom', :key => User.current.rss_key) %>
  <%= f.link_to_with_query_parameters('CSV', {}, :onclick => "showModal('csv-export-options', '350px'); return false;") %>
  <%= f.link_to_with_query_parameters('PDF') %>
<% end %>

<div id="csv-export-options" style="display: none;">
  <h3 class="title"><%= l(:label_export_options, :export_format => 'CSV') %></h3>
  <%= form_tag(@project ? roadmap_project_versions_path(@project, :format => 'csv') : roadmap_versions_path(:format => 'csv'), :method => :get, :id => 'csv-export-form') do %>
    <%= query_as_hidden_field_tags(@query) %>
    <p>
      <label><%= radio_button_tag('c[]', '', true) %> <%= l(:description_selected_columns) %></label><br />
      <label><%= radio_button_tag('c[]', 'all_inline') %> <%= l(:description_all_columns) %></label>
    </p>
    <p class="buttons">
      <%= submit_tag(l(:button_export), :name => nil, :onclick => "hideModal(this);") %>
      <%= submit_tag(l(:button_cancel), :name => nil, :onclick => "hideModal(this);", :type => 'button') %>
    </p>
  <% end %>
</div>

<% content_for :sidebar do %>
  <%= render_sidebar_queries(VersionQuery, @project) %>
<% end %>

<% content_for :header_tags do %>
  <%= auto_discovery_link_tag(:atom, { :query_id => @query, :format => 'atom', :page => nil, :key => User.current.rss_key }, :title => l(:label_version_plural)) %>
<% end %>

app/views/roadmap/index.pdf.erb
<%= raw versions_to_pdf(@versions, @project, @query) %>